# Generated by Django 2.2 on 2019-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateMachineTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'START'), (1, 'TRANSITION_TO_MIDDLE_ENABLED'), (2, 'MIDDLE'), (3, 'END'), (4, 'ANOTHER_END'), (5, 'THE_WAY_TO_FAILURE'), (6, 'FAILURE_IS_ACTUALLY_AN_OPTION'), (7, 'FAIL')], default=0)),
                ('can_transition_to_middle', models.BooleanField(default=False)),
            ],
        ),
    ]
